# -*- coding: utf-8 -*-
"""trimodal_bind_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvfBvzVdzlMARW6ouXqiWvg6a6uaUBzP
"""

!pip -q install torch torchvision torchaudio
!pip -q install transformers timm librosa gradio datasets

!pip -q install diffusers transformers accelerate

import os

folders = [
    "trimodal-bind",
    "trimodal-bind/data",
    "trimodal-bind/src",
    "trimodal-bind/src/models",
    "trimodal-bind/src/datasets",
    "trimodal-bind/src/utils",
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project folders created successfully.")

import torch
import torchvision
import torchaudio
import transformers
import timm

print("Torch:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

import torch
import torch.nn as nn
import torch.nn.functional as F

import timm
from transformers import AutoModel, AutoTokenizer

class ImageEncoder(nn.Module):
    def __init__(self, embed_dim=256):
        super().__init__()
        self.backbone = timm.create_model("resnet18", pretrained=True, num_classes=0)
        self.proj = nn.Linear(512, embed_dim)

    def forward(self, x):
        x = self.backbone(x)
        x = self.proj(x)
        return F.normalize(x, dim=-1)


class AudioEncoder(nn.Module):
    def __init__(self, embed_dim=256):
        super().__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1,1))
        )
        self.proj = nn.Linear(64, embed_dim)

    def forward(self, x):
        x = self.cnn(x)
        x = x.flatten(1)
        x = self.proj(x)
        return F.normalize(x, dim=-1)


class TextEncoder(nn.Module):
    def __init__(self, embed_dim=256):
        super().__init__()
        self.backbone = AutoModel.from_pretrained("distilbert-base-uncased")
        self.proj = nn.Linear(768, embed_dim)

    def forward(self, input_ids, attention_mask):
        out = self.backbone(input_ids=input_ids, attention_mask=attention_mask)
        cls = out.last_hidden_state[:,0,:]
        x = self.proj(cls)
        return F.normalize(x, dim=-1)

device = "cuda" if torch.cuda.is_available() else "cpu"

img_encoder = ImageEncoder().to(device)
aud_encoder = AudioEncoder().to(device)
txt_encoder = TextEncoder().to(device)

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

print("Models loaded on", device)

texts = ["dog barking", "car engine", "rain sound", "piano music"]

tok = tokenizer(
    texts,
    padding=True,
    truncation=True,
    return_tensors="pt"
)

# keep only fields DistilBERT needs
tok = {
    "input_ids": tok["input_ids"].to(device),
    "attention_mask": tok["attention_mask"].to(device)
}

with torch.no_grad():
    e1 = img_encoder(img)
    e2 = aud_encoder(aud)
    e3 = txt_encoder(**tok)

print(e1.shape, e2.shape, e3.shape)

import torch.nn.functional as F

def contrastive_loss(a, b, temperature=0.07):
    logits = (a @ b.T) / temperature

    labels = torch.arange(a.size(0)).to(a.device)

    loss_a = F.cross_entropy(logits, labels)
    loss_b = F.cross_entropy(logits.T, labels)

    return (loss_a + loss_b) / 2

def tri_modal_loss(img_emb, aud_emb, txt_emb):
    loss_it = contrastive_loss(img_emb, txt_emb)
    loss_ia = contrastive_loss(img_emb, aud_emb)
    loss_at = contrastive_loss(aud_emb, txt_emb)

    return (loss_it + loss_ia + loss_at) / 3

loss = tri_modal_loss(e1, e2, e3)
print("Loss:", loss.item())

!wget https://github.com/karolpiczak/ESC-50/archive/master.zip
!unzip -q master.zip

!unzip -q master.zip

!ls

!ls ESC-50-master/audio | head

import pandas as pd

meta = pd.read_csv("ESC-50-master/meta/esc50.csv")
meta.head()

sorted(meta["category"].unique())

classes = [
    "dog",
    "rain",
    "helicopter",
    "clock_alarm",
    "chirping_birds"
]

mini = meta[meta["category"].isin(classes)].copy()

print("Samples:", len(mini))
mini[["filename", "category"]].head(10)

mini["text"] = mini["category"].str.replace("_", " ")
mini[["filename", "category", "text"]].head()

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
import os

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

os.makedirs("generated_images", exist_ok=True)

prompts = {
    "dog": "a realistic dog standing outdoors, high quality photo",
    "rain": "heavy rain falling in a city street, realistic photo",
    "helicopter": "a helicopter flying in blue sky, realistic photo",
    "clock_alarm": "a ringing alarm clock on table, realistic photo",
    "chirping_birds": "small birds sitting on tree branch, realistic photo"
}

for name, prompt in prompts.items():
    image = pipe(prompt).images[0]
    image.save(f"generated_images/{name}.png")

print("Images generated.")

from IPython.display import display
for c in prompts:
    display(Image.open(f"generated_images/{c}.png"))

import os
import librosa
import numpy as np
import pandas as pd
from PIL import Image

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

classes = [
    "dog",
    "rain",
    "helicopter",
    "clock_alarm",
    "chirping_birds"
]

mini = meta[meta["category"].isin(classes)].copy()
mini["text"] = mini["category"].str.replace("_", " ")

print(len(mini))
mini.head()

img_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

class TriModalDataset(Dataset):
    def __init__(self, df):
        self.df = df.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        category = row["category"]
        text = row["text"]

        # image
        img_path = f"generated_images/{category}.png"
        image = Image.open(img_path).convert("RGB")
        image = img_transform(image)

        # audio
        wav_path = f"ESC-50-master/audio/{row['filename']}"
        y, sr = librosa.load(wav_path, sr=16000)

        mel = librosa.feature.melspectrogram(
            y=y,
            sr=sr,
            n_mels=128
        )
        mel = librosa.power_to_db(mel)
        mel = torch.tensor(mel).float().unsqueeze(0)

        return image, mel, text

ds = TriModalDataset(mini)

img, mel, txt = ds[0]

print("Image:", img.shape)
print("Audio:", mel.shape)
print("Text:", txt)

from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    images, audios, texts = zip(*batch)

    # images
    images = torch.stack(images)

    # pad audio width dimension
    max_w = max(a.shape[-1] for a in audios)

    padded = []
    for a in audios:
        pad_w = max_w - a.shape[-1]
        a = torch.nn.functional.pad(a, (0, pad_w))
        padded.append(a)

    audios = torch.stack(padded)

    # tokenize text
    tok = tokenizer(
        list(texts),
        padding=True,
        truncation=True,
        return_tensors="pt"
    )

    return images, audios, tok

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

print("Tokenizer loaded.")

loader = DataLoader(
    ds,
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)

batch = next(iter(loader))

imgs, auds, toks = batch

print(imgs.shape)
print(auds.shape)
print(toks["input_ids"].shape)

import torch
import torch.nn as nn
import torch.nn.functional as F
import timm
from transformers import AutoModel

device = "cuda" if torch.cuda.is_available() else "cpu"

class ImageEncoder(nn.Module):
    def __init__(self, embed_dim=256):
        super().__init__()
        self.backbone = timm.create_model("resnet18", pretrained=True, num_classes=0)
        self.proj = nn.Linear(512, embed_dim)

    def forward(self, x):
        x = self.backbone(x)
        x = self.proj(x)
        return F.normalize(x, dim=-1)

class AudioEncoder(nn.Module):
    def __init__(self, embed_dim=256):
        super().__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(1,32,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32,64,3,padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1,1))
        )
        self.proj = nn.Linear(64, embed_dim)

    def forward(self, x):
        x = self.cnn(x)
        x = x.flatten(1)
        x = self.proj(x)
        return F.normalize(x, dim=-1)

class TextEncoder(nn.Module):
    def __init__(self, embed_dim=256):
        super().__init__()
        self.backbone = AutoModel.from_pretrained("distilbert-base-uncased")
        self.proj = nn.Linear(768, embed_dim)

    def forward(self, input_ids, attention_mask):
        out = self.backbone(input_ids=input_ids, attention_mask=attention_mask)
        cls = out.last_hidden_state[:,0,:]
        x = self.proj(cls)
        return F.normalize(x, dim=-1)

img_encoder = ImageEncoder().to(device)
aud_encoder = AudioEncoder().to(device)
txt_encoder = TextEncoder().to(device)

print("Encoders restored.")

params = list(img_encoder.parameters()) + \
         list(aud_encoder.parameters()) + \
         list(txt_encoder.parameters())

optimizer = torch.optim.AdamW(params, lr=1e-4)

print("Optimizer ready.")

import torch
import torch.nn.functional as F

def contrastive_loss(a, b, temperature=0.07):
    logits = (a @ b.T) / temperature
    labels = torch.arange(a.size(0)).to(a.device)

    loss_a = F.cross_entropy(logits, labels)
    loss_b = F.cross_entropy(logits.T, labels)

    return (loss_a + loss_b) / 2


def tri_modal_loss(img_emb, aud_emb, txt_emb):
    loss_it = contrastive_loss(img_emb, txt_emb)
    loss_ia = contrastive_loss(img_emb, aud_emb)
    loss_at = contrastive_loss(aud_emb, txt_emb)

    return (loss_it + loss_ia + loss_at) / 3

print("Loss functions restored.")

img_encoder.train()
aud_encoder.train()
txt_encoder.train()

imgs, auds, toks = next(iter(loader))

imgs = imgs.to(device)
auds = auds.to(device)

toks = {
    "input_ids": toks["input_ids"].to(device),
    "attention_mask": toks["attention_mask"].to(device)
}

optimizer.zero_grad()

img_emb = img_encoder(imgs)
aud_emb = aud_encoder(auds)
txt_emb = txt_encoder(**toks)

loss = tri_modal_loss(img_emb, aud_emb, txt_emb)

loss.backward()
optimizer.step()

print("Train Loss:", loss.item())

epochs = 5

for epoch in range(epochs):
    img_encoder.train()
    aud_encoder.train()
    txt_encoder.train()

    total_loss = 0

    for imgs, auds, toks in loader:
        imgs = imgs.to(device)
        auds = auds.to(device)

        toks = {
            "input_ids": toks["input_ids"].to(device),
            "attention_mask": toks["attention_mask"].to(device)
        }

        optimizer.zero_grad()

        img_emb = img_encoder(imgs)
        aud_emb = aud_encoder(auds)
        txt_emb = txt_encoder(**toks)

        loss = tri_modal_loss(img_emb, aud_emb, txt_emb)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(loader)

    print(f"Epoch {epoch+1}: Loss = {avg_loss:.4f}")

img_encoder.eval()
aud_encoder.eval()
txt_encoder.eval()

gallery = []

with torch.no_grad():
    for imgs, auds, toks in loader:
        imgs = imgs.to(device)
        auds = auds.to(device)

        toks = {
            "input_ids": toks["input_ids"].to(device),
            "attention_mask": toks["attention_mask"].to(device)
        }

        img_emb = img_encoder(imgs)
        aud_emb = aud_encoder(auds)
        txt_emb = txt_encoder(**toks)

        for i in range(imgs.size(0)):
            gallery.append({
                "img": img_emb[i].cpu(),
                "aud": aud_emb[i].cpu(),
                "txt": txt_emb[i].cpu()
            })

print("Gallery size:", len(gallery))

query = "dog"

tok = tokenizer([query], return_tensors="pt", padding=True, truncation=True)
tok = {k:v.to(device) for k,v in tok.items() if k in ["input_ids","attention_mask"]}

with torch.no_grad():
    q = txt_encoder(**tok)[0].cpu()

scores = []

for i, item in enumerate(gallery):
    sim = torch.dot(q, item["img"]).item()
    scores.append((sim, i))

scores.sort(reverse=True)

print("Top matches:", scores[:5])

gallery = []

img_encoder.eval()
txt_encoder.eval()

with torch.no_grad():
    for _, row in mini.iterrows():
        category = row["category"]
        text = row["text"]

        # image path
        img_path = f"generated_images/{category}.png"

        # image tensor
        from PIL import Image
        image = Image.open(img_path).convert("RGB")
        image_t = img_transform(image).unsqueeze(0).to(device)

        emb = img_encoder(image_t)[0].cpu()

        gallery.append({
            "label": text,
            "path": img_path,
            "emb": emb
        })

print("Gallery ready:", len(gallery))

def retrieve(query):
    tok = tokenizer(
        [query],
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    tok = {
        "input_ids": tok["input_ids"].to(device),
        "attention_mask": tok["attention_mask"].to(device)
    }

    with torch.no_grad():
        q = txt_encoder(**tok)[0].cpu()

    best_score = -999
    best_item = None

    for item in gallery:
        score = torch.dot(q, item["emb"]).item()

        if score > best_score:
            best_score = score
            best_item = item

    return best_item["path"], f"Prediction: {best_item['label']} | Score: {best_score:.3f}"

import gradio as gr

demo = gr.Interface(
    fn=retrieve,
    inputs=gr.Textbox(label="Enter text query"),
    outputs=[
        gr.Image(label="Retrieved Image"),
        gr.Textbox(label="Result")
    ],
    title="TriModal Bind Demo",
    description="Search images using text from a learned shared embedding space."
)

demo.launch(share=True)